eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/

server:
  port: 9020
  servlet:
    context-path: /admin.server

management:
  context-path: /actuator
  health:
    mail:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://112.74.177.170:3306/oil_station_map?Unicode=true&characterEncoding=UTF-8
    username: caihongwang
    password: hejinrong@520
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 30
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
  mvc:
    static-path-pattern: /static/**
    servlet:
      load-on-startup: 0
  resources:
    static-locations: classpath:/static/
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

xxl:
  job:
    accessToken:
    i18n:
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30


mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

