eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/

server:
  port: 9020

spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000


zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  add-proxy-headers: true
  routes:
    oauth2:
      path: /oilStationMap/**
      serviceId: oilStationMap
      stripPrefix: false

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9030/oilStationMap/oauth/token
      user-authorization-uri: http://localhost:9030/oilStationMap/oauth/authorize
    resource:
      user-info-uri: http://localhost:9030/oilStationMap/user
      prefer-token-info: false

