my:
  name: newMall

eureka:
  client:
    serviceUrl:
      defaultZone: http://112.74.177.170:9010/eureka/

server:
  port: 9040
  servlet:
    context-path: /newMall

spring:
  application:
    name: newMall
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/new_mall?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: caihongwang
    password: hejinrong@520
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
      database: 2
      host: 112.74.177.170
      port: 6379
      password:
      jedis:
        pool:
          max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 100 # 连接池中的最大空闲连接
          min-idle: 50 # 连接池中的最小空闲连接
          max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      timeout: 1000
      store-type: none

mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true

logging:
  config-locations: log4j2.xml