my:
  name: oilStationMap

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/

server:
  port: 9030
  servlet:
    context-path: /oilStationMap

#线上环境

spring:
  profiles: publish
  application:
    name: oilStationMap
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://112.74.177.170:3306/oil_station_map?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: caihongwang
    password: hejinrong@520
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 100 # 连接池中的最大空闲连接
          min-idle: 50 # 连接池中的最小空闲连接
          max-wait: -6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      timeout: 10000
      store-type: none
    #线程池配置参数
    task:
      pool:
        corePoolSize: 100 #设置核心线程数
        maxPoolSize: 500  #设置最大线程数
        keepAliveSeconds: 60 #设置线程活跃时间（秒）
        queueCapacity: 100 #设置队列容量
        threadNamePrefix: YZKJ-AsyncThread- # 线程名称前缀

mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true

logging:
  config-locations: log4j2.xml

xxl:
  job:
    accessToken:
    admin:
      address: http://127.0.0.1:9020/admin
    executor:
      appname: oil-station-map-server
      ip: 127.0.0.1
      port: 9999
      logpath: /opt/oilStationMap.server/logs
      logretentiondays: 30