my:
  name: oilStationMap

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/

server:
  port: 9030
  servlet:
    context-path: /oilStationMap

#线上环境

spring:
  profiles: publish
  application:
    name: oilStationMap
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/oil_station_map?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: caihongwang
    password: hejinrong@520
    hikari:
      pool-name: HikariCP
      minimum-idle: 20 # 此属性控制HikariCP尝试在池中维护的最小空闲连接数
      maximum-pool-size: 100 # 此属性控制允许池达到的最大大小，包括空闲和使用中的连接
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为
      idle-timeout: 60000 # 此属性控制允许连接在池中保持空闲状态的最长时间
      max-lifetime: 120000 # 此属性控制池中连接的最大生存期
      connection-timeout: 60000 # 此属性控制客户端（即您）等待来自池的连接的最大毫秒数
      connection-test-query: SELECT 1 # 如果您的驱动程序支持JDBC4，我们强烈建议不要设置此属性
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 100 # 连接池中的最大空闲连接
          min-idle: 50 # 连接池中的最小空闲连接
          max-wait: -6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      timeout: 10000
      store-type: none
  #线程池配置参数
  task:
    pool:
      corePoolSize: 100 #设置核心线程数
      maxPoolSize: 500  #设置最大线程数
      keepAliveSeconds: 60 #设置线程活跃时间（秒）
      queueCapacity: 100 #设置队列容量
      threadNamePrefix: YZKJ-AsyncThread- # 线程名称前缀
  #QQ邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: yzkj_yzkj@163.com #发送邮件的邮箱地址
    password:  JLPZZUQDTCOQUWXP #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 25 #端口号465或587
    from: yzkj_yzkj@163.com # 发送邮件的地址，和上面username一致
    default-encoding: utf-8
    #    host: smtp.qq.com #发送邮件服务器
    #    username: 976499921@qq.com #发送邮件的邮箱地址
    #    password:  qbpqvmswgbxfbfbf #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    #    properties.mail.smtp.port: 587 #端口号465或587
    #    from: 976499921@qq.com # 发送邮件的地址，和上面username一致
    #    default-encoding: utf-8
  #appium启动端口号
  appiumPortStr: 4723,4725,4727,4729
  thePublicIp: 127.0.0.1
  defaultCommodPath: /opt/defaultCommodPath
  imgFormatStr: bmp,pcx,png,jpg,jpeg,gif,tiff

mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true

logging:
  config-locations: log4j2.xml

xxl:
  job:
    accessToken:
    admin:
      address: http://127.0.0.1:9020/myAdmin
    executor:
      appname: oil-station-map-server
      ip: 127.0.0.1
      port: 9999
      logpath: /opt/oilStationMap.server/logs
      logretentiondays: 30